### ISSUE TITLE
Add a new sentence !!!

### ISSUE THREAD

**Issue by mathiddc** [Jerome1337/henri-facts#1]
Please, add THESE sentences
"Ne confond pas tes problèmes avec les miens !"
"Bing ça marche bien !"
"Bisous bisous !"
"Pendant 5 secondes l'argent tombait du ciel, pendant 5 secondes je me suis considéré comme un dieu"
"Tu sais pas ce que je serais capable de faire pour un steakhouse"

Part 2 is coming soon...

**Comment by soullivaneuh** [comment]
@mathiddc Any ETA for part 2? It is quite urgent.
